TYPE=VIEW
query=select `eteccommerce`.`estado`.`IDESTADO` AS `IDESTADO`,`eteccommerce`.`estado`.`SIGLA` AS `SIGLA`,`eteccommerce`.`estado`.`NOME` AS `NOME`,`eteccommerce`.`estado`.`CIDADE` AS `CIDADE` from `eteccommerce`.`estado` order by `eteccommerce`.`estado`.`NOME`
md5=0d4635cc5c46057462b70e7238a19626
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-11-29 00:29:28
create-version=2
source=SELECT IDESTADO,SIGLA,NOME,CIDADE FROM estado ORDER BY NOME
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `eteccommerce`.`estado`.`IDESTADO` AS `IDESTADO`,`eteccommerce`.`estado`.`SIGLA` AS `SIGLA`,`eteccommerce`.`estado`.`NOME` AS `NOME`,`eteccommerce`.`estado`.`CIDADE` AS `CIDADE` from `eteccommerce`.`estado` order by `eteccommerce`.`estado`.`NOME`
mariadb-version=100125
