-- COMANDO PRA LIGAR O BANCO DE DADOS: mysql -u root -p 
-- calcularCidades
DROP PROCEDURE IF EXISTS calcularCidades;
DELIMITER $$
CREATE PROCEDURE calcularCidades(IN pIDESTADO INT) 
BEGIN
    DECLARE vCIDADES INT;
    SELECT COUNT(*) INTO vCIDADES FROM cidade WHERE (IDESTADO=pIDESTADO);
    UPDATE estado SET CIDADE=vCIDADES WHERE IDESTADO=pIDESTADO;
END $$
DELIMITER ;

-- calcularProdutosMarca
DROP PROCEDURE IF EXISTS calcularProdutosMarca;
DELIMITER $$
CREATE PROCEDURE calcularProdutosMarca(IN pIDMARCA INT) 
BEGIN
    DECLARE vPRODUTOS INT;
    SELECT COUNT(*) INTO vPRODUTOS FROM produto WHERE (IDMARCA=pIDMARCA);
    UPDATE marca SET PRODUTOS=vPRODUTOS WHERE (IDMARCA=pIDMARCA);
END $$
DELIMITER ;

-- calcularProdutosUnidade
DROP PROCEDURE IF EXISTS calcularProdutosUnidade;
DELIMITER $$
CREATE PROCEDURE calcularProdutosUnidade(IN pIDUNIDADE INT) 
BEGIN
    DECLARE vPRODUTOS INT;
    SELECT COUNT(*) INTO vPRODUTOS FROM produto WHERE (IDUNIDADE=pIDUNIDADE);
    UPDATE unidade SET PRODUTOS=vPRODUTOS WHERE (IDUNIDADE=pIDUNIDADE);
END $$
DELIMITER ;








